services:
  database:
    container_name: next-database
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - next-database:/var/lib/postgresql/data
    networks:
      - next-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    shm_size: 128mb

  adminer:
    container_name: next-adminer
    image: adminer:latest
    command: php -S 0.0.0.0:8080 -t /var/www/html
    env_file:
      - .env
    environment:
      ADMINER_DEFAULT_DB_DRIVER: 'pgsql'
      ADMINER_DEFAULT_DB_HOST: next-database
      ADMINER_DEFAULT_DB_NAME: ${POSTGRES_DATABASE}
    ports:
      - '8080:8080'
    depends_on:
      - database
    networks:
      - next-network
    restart: unless-stopped

volumes:
  next-database:

networks:
  next-network:
    driver: bridge