services:
  nginx:
    container_name: next-nginx
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs
    networks:
      - next-network
    restart: always

  nextjs:
    container_name: next-app
    build:
      context: .
      dockerfile: next.Dockerfile
    env_file:
      - .env
    expose:
      - '3000'
    depends_on:
      database:
        condition: service_healthy
    networks:
      - next-network
    restart: always

  database:
    container_name: next-database
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    expose:
      - '5432'
    volumes:
      - next-database:/var/lib/postgresql/data
    networks:
      - next-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    shm_size: 256mb

volumes:
  next-database:

networks:
  next-network:
    driver: bridge